/**
 * Legal move generation, in the mover's frame (see board.js for the indexing).
 *
 * The unit here is one OpenSpiel *decision*, not one backgammon turn: a plain
 * roll is a decision of up to two half-moves, and a double is two consecutive
 * decisions of up to two half-moves each (the second with midDoubles set, the
 * same player still on roll). That is how the Python engine sees the game, and
 * the demo has to see it the same way — the published strength numbers were
 * measured with doubles staged exactly like this.
 *
 * The output is a set of resulting positions, deduplicated by boardKey: two
 * move orders reaching the same position are one candidate as far as a 0-ply
 * engine is concerned, and OpenSpiel's action indices are never ported.
 *
 * tests/movegen.test.js checks this file against ~2,000 positions generated by
 * OpenSpiel itself, including bar, bear-off, doubles and mid-doubles cases.
 */

import { BAR, OFF, POINTS, canBearOff, clonePosition, boardKey } from "./board.js";

/** Half-moves available to the mover with one die. */
export function halfMoves(pos, die) {
  const moves = [];

  if (pos.myBar > 0) {
    const to = POINTS - die;
    if (pos.opp[to] <= 1) moves.push({ from: BAR, to, die, hit: pos.opp[to] === 1 });
    return moves; // entering is compulsory while a checker sits on the bar
  }

  for (let from = 0; from < POINTS; from++) {
    if (pos.my[from] === 0) continue;
    const to = from - die;
    if (to >= 0) {
      if (pos.opp[to] <= 1) moves.push({ from, to, die, hit: pos.opp[to] === 1 });
      continue;
    }
    if (!canBearOff(pos)) continue;
    if (to === -1) {
      moves.push({ from, to: OFF, die, hit: false }); // exact roll
    } else if (!higherCheckerThan(pos, from)) {
      moves.push({ from, to: OFF, die, hit: false }); // overshoot, nothing behind
    }
  }
  return moves;
}

function higherCheckerThan(pos, from) {
  for (let i = from + 1; i < 6; i++) if (pos.my[i] > 0) return true;
  return false;
}

/** Apply one half-move, returning a new position. */
export function applyHalfMove(pos, mv) {
  const next = clonePosition(pos);
  if (mv.from === BAR) next.myBar -= 1;
  else next.my[mv.from] -= 1;

  if (mv.to === OFF) {
    next.myOff += 1;
  } else {
    next.my[mv.to] += 1;
    if (mv.hit) {
      next.opp[mv.to] = 0;
      next.oppBar += 1;
    }
  }
  return next;
}

/**
 * Every legal play for one decision.
 *
 * Returns [{ position, moves }], deduplicated by resulting position and sorted
 * by boardKey so the order is stable for tests and for the analysis panel.
 * A player with nothing to play yields a single entry with no moves, matching
 * OpenSpiel's pass action.
 */
export function legalPlays(pos, dice) {
  const seen = new Map();
  for (const play of legalSequences(pos, dice)) {
    const key = boardKey(play.position);
    if (!seen.has(key)) seen.set(key, { ...play, key });
  }
  return [...seen.values()].sort((a, b) => (a.key < b.key ? -1 : a.key > b.key ? 1 : 0));
}

/**
 * Every legal *order* of half-moves, not just every reachable position.
 *
 * The engine ranks positions, so legalPlays() collapses transpositions. A human
 * dragging checkers picks an order, though, and the order they pick has to be
 * allowed even when another order reaches the same place — so the board UI
 * validates clicks against this list instead.
 */
export function legalSequences(pos, dice) {
  const [d1, d2] = dice;
  const doubles = d1 === d2;
  // A decision spends at most two dice: both halves of a plain roll, or two of
  // the four a double is worth (the other two belong to the next decision).
  const pool = doubles ? [d1, d1] : [d1, d2];

  const leaves = [];
  explore(pos, pool, [], leaves);

  let best = maxUsed(leaves);

  // Rule of the higher die: if only one die can be played and they differ, the
  // larger one must be used when a play with it exists.
  if (best.used === 1 && !doubles) {
    const high = Math.max(d1, d2);
    const withHigh = best.plays.filter((p) => p.moves[0].die === high);
    if (withHigh.length > 0) best = { used: 1, plays: withHigh };
  }
  return best.plays;
}

function explore(pos, dice, path, leaves) {
  let extended = false;
  const tried = new Set();
  for (let i = 0; i < dice.length; i++) {
    if (tried.has(dice[i])) continue; // equal dice: one ordering is enough
    tried.add(dice[i]);
    const rest = dice.slice(0, i).concat(dice.slice(i + 1));
    for (const mv of halfMoves(pos, dice[i])) {
      extended = true;
      explore(applyHalfMove(pos, mv), rest, [...path, mv], leaves);
    }
  }
  if (!extended) leaves.push({ position: pos, moves: path });
}

/** Keep only the plays using the most dice — using both is compulsory when possible. */
function maxUsed(leaves) {
  let used = 0;
  for (const leaf of leaves) used = Math.max(used, leaf.moves.length);
  return { used, plays: leaves.filter((l) => l.moves.length === used) };
}

/**
 * Does the mover get another decision after this one?
 *
 * Only on a double, only from its first decision (`midDoubles` says the other
 * two half-moves are already spent — a double is worth four, not six), only
 * when two half-moves were actually played, and only if something is still
 * playable. Mirrors OpenSpiel, which ends the turn by offering a pass rather
 * than a second decision when nothing is left.
 */
export function hasSecondDecision(position, dice, play, { midDoubles = false } = {}) {
  if (dice[0] !== dice[1]) return false;
  if (midDoubles) return false;
  if (play.moves.length < 2) return false;
  return halfMoves(position, dice[0]).length > 0;
}
